# Generated by Django 2.0 on 2017-12-17 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20171217_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
