# Generated by Django 2.0 on 2017-12-18 13:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20171218_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='datetime',
        ),
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Publication date'),
        ),
    ]
